# Generated by Django 2.1.2 on 2018-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
