# Generated by Django 2.1.2 on 2018-12-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20181207_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='myid',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
